spring.application.name=employeeAuth
logging.level.com.devBackend.employeeAuth=${APP_LOG_LEVEL:INFO}

spring.mongodb.uri=${MONGODB_URI}
mongodb.collections.envelopes=${MONGODB_COLLECTION_ENVELOPES:employessCollection}

security.jwt.secret=${JWT_SECRET:c7d39e3f-57dc-4c16-b2e2-99f550508727}
security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:2}
