spring.application.name=employeeAuth
server.port=8081
logging.level.com.devBackend.employeeAuth=${APP_LOG_LEVEL:INFO}

spring.mongodb.uri=mongodb+srv://activityDb:YaXKllClkFZKHbdp@workoutcluster.town7g3.mongodb.net/workoutApplication?appName=workoutCluster
mongodb.collections.employees=employessCollection

security.jwt.secret=c7d39e3f-57dc-4c16-b2e2-99f550508727
security.jwt.expiration-hours=24
