spring.application.name=employAuth
logging.level.com.devBackend.employAuth=${APP_LOG_LEVEL:INFO}

spring.mongodb.uri=${MONGODB_URI}
mongodb.collections.envelopes=${MONGODB_COLLECTION_ENVELOPES:employessCollection}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:2}
